permalink: /:categories/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

title: vkethana.com
description: Vijay's personal website

author:
  name: Vijay Kethanaboyina
  url: https://vkethana.com

twitter: 
  username: v_kethana
  card: summary
